import type { MetadataRoute } from 'next';

/**
 * robots.txt — Auto-generated by Next.js at /robots.txt
 *
 * URL resolution:
 *   - Uses NEXT_PUBLIC_SITE_URL env var (set in hosting dashboard)
 *   - Falls back to VERCEL_URL (auto-provided by Vercel)
 *   - Falls back to localhost for local development
 *
 * IMPORTANT: Never hardcode an e2b.app or temporary preview URL here.
 */
function getBaseUrl(): string {
  if (
    process.env.NEXT_PUBLIC_SITE_URL &&
    !process.env.NEXT_PUBLIC_SITE_URL.includes('YOUR_PRODUCTION_DOMAIN') &&
    !process.env.NEXT_PUBLIC_SITE_URL.includes('localhost')
  ) {
    return process.env.NEXT_PUBLIC_SITE_URL.replace(/\/$/, '');
  }
  if (process.env.VERCEL_URL) {
    return `https://${process.env.VERCEL_URL}`;
  }
  return 'http://localhost:3000';
}

export default function robots(): MetadataRoute.Robots {
  const baseUrl = getBaseUrl();

  return {
    rules: [
      {
        // All crawlers — allow public pages, block private ones
        userAgent: '*',
        allow: [
          '/',
          '/about',
          '/terminal',
          '/ai-assistant',
          '/journal',
          '/portfolio',
          '/pricing',
          '/support',
          '/whats-new',
          '/og-image.jpg',
          '/icon-192.png',
          '/icon-512.png',
          '/favicon.svg',
        ],
        disallow: [
          '/admin',
          '/settings',
          '/api/',
          '/_next/',
          '/api/auth/',
        ],
      },
      {
        // Googlebot — explicitly allow for clarity
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/about',
          '/terminal',
          '/ai-assistant',
          '/journal',
          '/portfolio',
          '/pricing',
          '/support',
          '/whats-new',
        ],
        disallow: [
          '/admin',
          '/settings',
          '/api/',
        ],
      },
      {
        // Bingbot
        userAgent: 'Bingbot',
        allow: ['/'],
        disallow: ['/admin', '/settings', '/api/'],
      },
    ],
    sitemap:  `${baseUrl}/sitemap.xml`,
    host:     baseUrl,
  };
}
