import type { MetadataRoute } from 'next';

/**
 * sitemap.xml — Auto-generated by Next.js at /sitemap.xml
 *
 * All URLs are built from environment variables — never hardcoded.
 * The sitemap updates automatically on every deployment.
 */
function getBaseUrl(): string {
  if (
    process.env.NEXT_PUBLIC_SITE_URL &&
    !process.env.NEXT_PUBLIC_SITE_URL.includes('YOUR_PRODUCTION_DOMAIN') &&
    !process.env.NEXT_PUBLIC_SITE_URL.includes('localhost')
  ) {
    return process.env.NEXT_PUBLIC_SITE_URL.replace(/\/$/, '');
  }
  if (process.env.VERCEL_URL) {
    return `https://${process.env.VERCEL_URL}`;
  }
  return 'http://localhost:3000';
}

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = getBaseUrl();
  const now = new Date();

  return [
    // ── Homepage — highest priority ──────────────────────────
    {
      url:             baseUrl,
      lastModified:    now,
      changeFrequency: 'daily',
      priority:        1.0,
    },
    // ── About Himanshu — high priority (brand keyword) ───────
    {
      url:             `${baseUrl}/about`,
      lastModified:    now,
      changeFrequency: 'weekly',
      priority:        0.9,
    },
    // ── Trading Terminal — core feature ───────────────────────
    {
      url:             `${baseUrl}/terminal`,
      lastModified:    now,
      changeFrequency: 'daily',
      priority:        0.9,
    },
    // ── AI Assistant ─────────────────────────────────────────
    {
      url:             `${baseUrl}/ai-assistant`,
      lastModified:    now,
      changeFrequency: 'weekly',
      priority:        0.8,
    },
    // ── Trade Journal ─────────────────────────────────────────
    {
      url:             `${baseUrl}/journal`,
      lastModified:    now,
      changeFrequency: 'weekly',
      priority:        0.8,
    },
    // ── Pricing — conversion page ─────────────────────────────
    {
      url:             `${baseUrl}/pricing`,
      lastModified:    now,
      changeFrequency: 'monthly',
      priority:        0.8,
    },
    // ── Portfolio & Alerts ────────────────────────────────────
    {
      url:             `${baseUrl}/portfolio`,
      lastModified:    now,
      changeFrequency: 'weekly',
      priority:        0.7,
    },
    // ── What's New / Changelog ────────────────────────────────
    {
      url:             `${baseUrl}/whats-new`,
      lastModified:    now,
      changeFrequency: 'weekly',
      priority:        0.7,
    },
    // ── Help Center / Support ─────────────────────────────────
    {
      url:             `${baseUrl}/support`,
      lastModified:    now,
      changeFrequency: 'monthly',
      priority:        0.6,
    },
    // ── Admin, Settings — excluded (private, noindex) ─────────
    // Do NOT add /admin or /settings to the sitemap
  ];
}
